# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
